# Generated by Django 2.1.5 on 2022-10-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='photo_preview',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
